# DEVELOPMENT CONFIG

livereload: true
include:
  - _assets
  - node_modules/@fortawesome/fontawesome-free/webfonts/fa-brands-400.woff2
  - node_modules/@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2
  - node_modules/prismjs/themes/prism-tomorrow.css
  - node_modules/prismjs/plugins/toolbar/prism-toolbar.css
  - node_modules/prismjs/prism.js
  - node_modules/prismjs/components/prism-markup.js
  - node_modules/prismjs/components/prism-css.js
  - node_modules/prismjs/components/prism-clike.js
  - node_modules/prismjs/components/prism-javascript.js
  - node_modules/prismjs/components/prism-markdown.js
  - node_modules/prismjs/components/prism-bash.js
  - node_modules/prismjs/plugins/show-language/prism-show-language.min.js
  - node_modules/prismjs/plugins/toolbar/prism-toolbar.min.js
  - node_modules/prismjs/plugins/copy-to-clipboard/prism-copy-to-clipboard.min.js
sass:
  sass_dir: _assets/css/_sass
  # style: compressed